<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => 'ce6f2e92256a6d911f2e4e59111f6e4c',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/liligiroud',
  'STRIPE_PUBLIC_KEY' => 'pk_test_51Lg922LJwimzi8fIh91LoPyec5a9uM40ilZVwUHQZbeUOZZRxHgjpMFleYnSOgyCTibVmchEF1x4tIjAfpCOU7C700cTLBQWGH',
  'STRIPE_SECRET_KEY' => 'sk_test_51Lg922LJwimzi8fInuIPsPttiK3tcuvQQYxbeYzoi1Hv0cj31VA1F5EC0RjRwyd70rbdieBkBnIx5SJuNMsN96D400ejGBftSR',
  'API_MAIL_JET_KEY' => '62cef08a7ebd1ecddcde9f94be61bcb9',
  'API_MAIL_JET_SECRET' => '182313ff27db74ec8edc0dd973fd4fa8',
);
